s1[0]="A"
s1[1]="B"
s1[image]="alexpedo/p4"


s2[0]="C"
s2[1]="B"
s2[image]="alexpedo/p4"


modbusclient[0]="A"
modbusclient[image]="alexpedo/mod_cl"


modbusserver[0]="C"
modbusserver[image]="alexpedo/mod_cl"

wireshark[0]="A"
wireshark[1]="B"
wireshark[2]="C"
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark"
